#!/usr/bin/env bash
# Regenerate docs/neighbours.tsv: which forge-kit components share a name with a component shipped
# by a neighbouring marketplace, and how far apart the two files are (#177).
#
#   neighbour-manifest.sh --refresh [--marketplaces DIR] [--root DIR]
#
# THIS IS A MAINTAINER COMMAND, NOT A BUILD STEP. It reads the marketplaces installed on this
# machine (~/.claude/plugins/marketplaces by default), which CI does not have. The guard that runs
# in CI, check-neighbour-overlap.sh, reads only the file this writes.
#
# WHY THE MANIFEST AND THIS SCRIPT ARE ONE DELIVERABLE. A list of what the neighbours ship is a
# SNAPSHOT, and a snapshot with no refresh path is a claim that quietly stops being true. That is
# the failure this repository keeps finding in its own guards, so the refresh ships with the list
# and the list records the date it was taken.
#
# WHAT IT CANNOT SEE, stated here because a guard that overstates its reach is worse than a narrow
# one that admits it:
#   - a component copied from a neighbour under a DIFFERENT name. Nothing name-based can see that.
#   - a neighbour that is not installed on the machine running the refresh.
#   - anything that changed upstream since the last refresh.
set -uo pipefail

MK="${HOME}/.claude/plugins/marketplaces"
ROOT="$(git rev-parse --show-toplevel 2>/dev/null || echo .)"
MODE=""
while [ $# -gt 0 ]; do
  case "$1" in
    --refresh) MODE=refresh; shift ;;
    --marketplaces) MK="$2"; shift 2 ;;
    --root) ROOT="$2"; shift 2 ;;
    *) echo "neighbour-manifest: unknown argument '$1'" >&2; exit 2 ;;
  esac
done
[ "$MODE" = refresh ] || { echo "neighbour-manifest: --refresh is required (this rewrites docs/neighbours.tsv)" >&2; exit 2; }
[ -d "$MK" ] || { echo "neighbour-manifest: no marketplaces directory at $MK" >&2; exit 2; }
cd "$ROOT" || exit 2

OUT=docs/neighbours.tsv
TODAY=$(date +%Y-%m-%d)

# THE THRESHOLD, and why it is not a coin flip. Measured across all 18 name matches in this tree on
# 2026-09-10, AFTER the normalisation below: the files that are the same file differ by 1, 1, 5, 9
# and 10 lines. The nearest genuine divergence is 103, and full-review, which added the iteration
# contract to a shared ancestor, is 173. Nothing at all sits between 10 and 103, so a cut anywhere
# in that gap gives the same answer and 25 is comfortably inside it. Re-measure before moving it.
#
# `duplicate` fails the build. `collision` does not: `code-reviewer` is a name anyone would pick,
# and a guard that treats every shared name as a defect gets switched off, which is worse than not
# having one.
DUP_MAX=25

norm() {
  # Strip the two things that always differ and never matter: the frontmatter `name:` (neighbours
  # prefix theirs with their plugin) and our version marker. Whitespace is trimmed so an editor
  # cannot manufacture a difference.
  sed -e '/^name:[[:space:]]/d' -e '/-version:[[:space:]]*[0-9]*[[:space:]]*-->/d' \
      -e '/^#[[:space:]]*[a-z0-9-]*-version:[[:space:]]*[0-9]*$/d' -e 's/[[:space:]]*$//' "$1"
}

{
  printf '# Generated by scripts/neighbour-manifest.sh --refresh. Do not hand-edit.\n'
  printf '# Every forge-kit component whose NAME is also shipped by an installed neighbouring\n'
  printf '# marketplace. verdict=duplicate means the two files are the same file (see DUP_MAX in\n'
  printf '# the generator); verdict=collision means two projects picked the same obvious name.\n'
  printf '# measured is the day the comparison ran: it ages, and the guard says so.\n'
  printf 'marketplace\tplugin\tkind\tname\ttheir_lines\tour_lines\tdiffering\tverdict\tmeasured\n'
} > "$OUT"

rows=0
for own in plugins/*/agents/*.md plugins/*/commands/*.md plugins/*/skills/*/SKILL.md; do
  [ -f "$own" ] || continue
  base=$(basename "$own")
  if [ "$base" = "SKILL.md" ]; then name=$(basename "$(dirname "$own")"); kind=skill
  else name="${base%.md}"; case "$own" in */agents/*) kind=agent ;; *) kind=command ;; esac; fi

  for mkdir_ in "$MK"/*; do
    [ -d "$mkdir_" ] || continue
    mkname=$(basename "$mkdir_")
    [ "$mkname" = "forge-kit" ] && continue          # our own checkout is not a neighbour
    hit=$(find "$mkdir_" \( -path "*/agents/$name.md" -o -path "*/commands/$name.md" -o -path "*/skills/$name/SKILL.md" \) 2>/dev/null | head -1)
    [ -n "$hit" ] || continue
    plug=${hit#"$mkdir_"/}
    plug=${plug#plugins/}
    plug=${plug%%/*}
    d=$(diff <(norm "$hit") <(norm "$own") | grep -c '^[<>]')
    if [ "$d" -le "$DUP_MAX" ]; then verdict=duplicate; else verdict=collision; fi
    printf '%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n' \
      "$mkname" "$plug" "$kind" "$name" "$(wc -l < "$hit" | tr -d ' ')" "$(wc -l < "$own" | tr -d ' ')" "$d" "$verdict" "$TODAY" >> "$OUT"
    rows=$((rows + 1))
  done
done

echo "neighbour-manifest: $rows row(s) written to $OUT from $MK"
