#!/usr/bin/env python3
"""Render the component inventory into marker-delimited regions, or check they are fresh.

Issue #96. The inventory was hand-maintained prose in several places and nothing checked it
against the tree, so it drifted repeatedly and was caught only by review agents. At the time this
landed, README.md claimed "14 skills" and omitted mutation-sweep, which had shipped in PR #93.
The tree is now the only authority; these regions are generated from it.

Python rather than bash, unlike the other root scripts, because this one is marker-region
rewriting and diffing rather than globbing and grepping, and that is where bash quoting bugs
hide. The extraction half stays in bash: this shells out to forge-adapt-catalogue.sh --tsv so
"what counts as a component" keeps exactly one definition, in the script forge-adapt already runs.

Usage:
  update-component-index.py [--check] [--root DIR]

  default   rewrite the regions in place, report what changed
  --check   exit 1 if any region is stale, printing the offending region (for CI)
"""
import argparse
import ast
import json
import os
import re
import subprocess
import sys

# Ordering is part of the output contract: the regions must be byte-stable across runs, or
# --check fails on noise. Glob order already sorts within a type; this fixes the type order.
TYPE_ORDER = {"subagent": 0, "command": 1, "skill": 2, "hook": 3, "asset": 4}
TYPE_LABEL = {
    "subagent": "agent",
    "command": "command",
    "skill": "skill",
    "hook": "hook",
    "asset": "shell asset",
}
DESC_CAP = 120
# The catalogue column is the primary answer to "what would I get", so it gets more room than the
# per-component excerpt, which sits above a table naming every component anyway.
CATALOGUE_DESC_CAP = 200

_PLUGIN_SEMVERS = {}
_PLUGIN_DESCRIPTIONS = {}

# The component version marker, skipped by the comment fallback so a hook is not described
# as "block-dashes-version: 5".
_MARKER_LINE = re.compile(r"^#\s*[a-z0-9-]+-version:\s*\d+\s*$")

NOTICE = (
    "<!-- Generated by scripts/update-component-index.py from the plugins/ tree. "
    "Do not hand-edit: run the script. CI fails on a stale region. -->"
)


def catalogue(root):
    """Component rows straight from the shared extractor. Never re-walk the tree here."""
    script = os.path.join(root, "scripts", "forge-adapt-catalogue.sh")
    out = subprocess.run(
        ["bash", script, "--tsv", root],
        capture_output=True, text=True, check=True,
    ).stdout
    rows = []
    for line in out.splitlines():
        if not line.strip():
            continue
        group, ctype, name, version, path = line.split("\t")
        rows.append({
            "group": group, "type": ctype, "name": name,
            "version": version, "path": path,
        })
    rows.sort(key=lambda r: (r["group"], TYPE_ORDER.get(r["type"], 9), r["name"]))
    return rows


def _frontmatter_description(text):
    """description: from YAML frontmatter, including folded/block scalars (7 files use them).

    Hand-rolled rather than PyYAML: forge-kit deliberately has no package manager, and a
    generator that needs a pip install would be the first dependency in the repo.
    """
    if not text.startswith("---\n"):
        return None
    end = text.find("\n---", 3)
    if end == -1:
        return None
    block = text[4:end].splitlines()
    for i, line in enumerate(block):
        m = re.match(r"^description:\s*(.*)$", line)
        if not m:
            continue
        value = m.group(1).strip()
        if value in (">", ">-", "|", "|-", ">+", "|+"):
            # Block scalar: take the following lines that are indented under it.
            parts = []
            for cont in block[i + 1:]:
                if cont.strip() and not cont.startswith((" ", "\t")):
                    break
                parts.append(cont.strip())
            value = " ".join(p for p in parts if p)
        else:
            # A plain scalar may still wrap onto indented continuation lines.
            parts = [value]
            for cont in block[i + 1:]:
                if not cont.startswith((" ", "\t")) or not cont.strip():
                    break
                parts.append(cont.strip())
            value = " ".join(parts)
        return value.strip().strip('"').strip("'")
    return None


def _fallback_description(path, text):
    """No frontmatter description: 3 commands, 4 hooks and 3 shell assets.

    Reading the prose that is already there beats leaving a quarter of the table blank, and it
    adds no new frontmatter requirement to any component. Each shape keeps its own rule, because
    a single "first comment line" rule picks up the version marker and reports a component's
    description as "block-dashes-version: 5".
    """
    if path.endswith(".py"):
        try:
            doc = ast.get_docstring(ast.parse(text))
        except SyntaxError:
            doc = None
        if doc:
            return doc.strip()
    if path.endswith((".py", ".sh")):
        for line in text.splitlines():
            if line.startswith("#!") or _MARKER_LINE.match(line):
                continue
            if line.startswith("#"):
                body = line.lstrip("#").strip()
                if body:
                    return body
            elif line.strip():
                break
        return ""
    # Markdown: the first PARAGRAPH, not the first line. A sentence routinely wraps, and taking
    # one line truncates it mid-clause.
    para, started = [], False
    for line in text.splitlines():
        s_ = line.strip()
        if not started:
            if not s_ or s_.startswith(("<!--", "#", "---", "```", "|", ">")):
                continue
            started = True
            para.append(s_)
        else:
            if not s_ or s_.startswith(("<!--", "#", "```", "|")):
                break
            para.append(s_)
    return " ".join(para)


# Periods that do not end a sentence. Without this, block-legacy-host-push's description was
# cut to "...after a forge migration (e.g." because the splitter fired on the abbreviation.
_ABBREV = {"e.g", "i.e", "etc", "vs", "cf", "approx", "sh", "py"}


def _first_sentence(text):
    for m in re.finditer(r"[.!?](?=\s|$)", text):
        word = re.search(r"([A-Za-z.]+)$", text[: m.start()])
        if word:
            # Only an alphabetic token can be an abbreviation. A period after ")" or a digit
            # ends a sentence, and treating "no token" as suspicious swallowed the real end of
            # "...(GitHub | Forgejo)." and ran on into the next line.
            token = word.group(1).lower()
            if token in _ABBREV or len(token.replace(".", "")) <= 1:
                continue
        return text[: m.end()]
    return text


def describe(path):
    try:
        with open(path, encoding="utf-8") as fh:
            text = fh.read()
    except OSError:
        return ""
    desc = _frontmatter_description(text)
    if desc is None:
        desc = _fallback_description(path, text)
    desc = re.sub(r"\s+", " ", desc or "").strip()
    # First sentence, then a hard cap: frontmatter descriptions are written as trigger text for
    # the model and run to several hundred characters.
    desc = _first_sentence(desc)
    if len(desc) > DESC_CAP:
        desc = desc[: DESC_CAP - 1].rstrip() + "…"
    return desc.replace("|", "\\|")


# Word counts make size a reviewable fact on every PR (issue #97): a budget whose numbers are
# invisible is prose nobody enforces. Prose components only. A count for a .py hook or a .sh asset
# would be a number with no meaning, and scripts/check-component-size.sh skips those types too.
_SIZED_TYPES = ("subagent", "command", "skill")


def word_count(row):
    if row["type"] not in _SIZED_TYPES:
        return ""
    try:
        with open(row["path"], encoding="utf-8") as fh:
            return str(len(fh.read().split()))
    except OSError:
        return ""


def render_component_index(rows):
    """The full inventory, for README.md."""
    counts = {}
    for r in rows:
        counts[r["type"]] = counts.get(r["type"], 0) + 1
    summary = ", ".join(
        "%d %s%s" % (counts[t], TYPE_LABEL[t], "" if counts[t] == 1 else "s")
        for t in sorted(counts, key=lambda t: TYPE_ORDER.get(t, 9))
    )
    groups = len({r["group"] for r in rows})
    out = [
        NOTICE,
        "",
        "**%d components across %d plugin groups:** %s." % (len(rows), groups, summary),
        "",
        "| Plugin group | Type | Component | Version | Words | What it does |",
        "|---|---|---|---|---:|---|",
    ]
    for r in rows:
        out.append("| `%s` | %s | `%s` | v%s | %s | %s |" % (
            r["group"], TYPE_LABEL[r["type"]], r["name"], r["version"],
            word_count(r), describe(r["path"]),
        ))
    return "\n".join(out)


def render_plugin_groups(rows):
    """The compact per-group table, for CLAUDE.md."""
    out = [
        NOTICE,
        "",
        "| Plugin group | Version | Contents |",
        "|---|---|---|",
    ]
    for group in sorted({r["group"] for r in rows}):
        members = [r for r in rows if r["group"] == group]
        parts = []
        for t in sorted({m["type"] for m in members}, key=lambda t: TYPE_ORDER.get(t, 9)):
            names = [m["name"] for m in members if m["type"] == t]
            label = TYPE_LABEL[t] + ("" if len(names) == 1 else "s")
            parts.append("%s: %s" % (label, ", ".join(names)))
        out.append("| `%s` | %s | %s |" % (group, plugin_version(group), "; ".join(parts)))
    return "\n".join(out)


def render_plugin_catalogue(rows):
    """The user-facing group table, for README.md.

    A separate region from render_plugin_groups rather than a shared one: CLAUDE.md's table answers
    "what is in this repo" and lists every component by name, while this one answers "what would I
    install and why", so it carries the install command and the group's own description. Generated
    for the same reason as the others, because a hand-maintained install command is a copy of a
    string that rots (#96), and README's group table did not exist at all until someone tried to
    install a group and found the command written down nowhere.
    """
    out = [
        NOTICE,
        "",
        "| Plugin group | Version | Install | What you get |",
        "|---|---|---|---|",
    ]
    for group in sorted({r["group"] for r in rows}):
        desc = _PLUGIN_DESCRIPTIONS.get(group, "")
        if len(desc) > CATALOGUE_DESC_CAP:
            desc = desc[: CATALOGUE_DESC_CAP - 1].rstrip() + "\u2026"
        out.append(
            "| `%s` | %s | `claude plugin install %s@forge-kit` | %s |"
            % (group, plugin_version(group), group, desc)
        )
    return "\n".join(out)


def plugin_version(group):
    return _PLUGIN_SEMVERS.get(group, "?")


def load_plugin_semvers(root):
    """The unit-of-install version, read from each group's plugin.json (docs/guides/versioning.md
    level 2). Shown beside the component markers so the table does not conflate the two."""
    base = os.path.join(root, "plugins")
    for group in sorted(os.listdir(base)):
        pj = os.path.join(base, group, ".claude-plugin", "plugin.json")
        if os.path.isfile(pj):
            with open(pj, encoding="utf-8") as fh:
                manifest = json.load(fh)
            _PLUGIN_SEMVERS[group] = manifest.get("version", "?")
            _PLUGIN_DESCRIPTIONS[group] = " ".join(manifest.get("description", "").split())


REGIONS = [
    ("README.md", "plugin-catalogue", render_plugin_catalogue),
    ("README.md", "component-index", render_component_index),
    ("CLAUDE.md", "plugin-groups", render_plugin_groups),
]


def replace_region(text, region_id, body, path):
    start = "<!-- %s:start -->" % region_id
    end = "<!-- %s:end -->" % region_id
    si, ei = text.find(start), text.find(end)
    if si == -1 or ei == -1:
        raise SystemExit(
            "update-component-index: %s has no '%s' region. Add the marker pair:\n%s\n%s"
            % (path, region_id, start, end)
        )
    if ei < si:
        raise SystemExit(
            "update-component-index: %s has '%s' markers in the wrong order" % (path, region_id)
        )
    return text[: si + len(start)] + "\n" + body + "\n" + text[ei:]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if a region is stale instead of rewriting it")
    ap.add_argument("--root", default=None, help="forge-kit tree to operate on")
    args = ap.parse_args()

    root = args.root or os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    load_plugin_semvers(root)
    rows = catalogue(root)
    if not rows:
        raise SystemExit("update-component-index: catalogue returned no components under " + root)

    stale, changed = [], []
    for filename, region_id, render in REGIONS:
        path = os.path.join(root, filename)
        with open(path, encoding="utf-8") as fh:
            text = fh.read()
        updated = replace_region(text, region_id, render(rows), path)
        if updated == text:
            continue
        if args.check:
            stale.append(filename)
        else:
            with open(path, "w", encoding="utf-8") as fh:
                fh.write(updated)
            changed.append(filename)

    if args.check:
        if stale:
            print("update-component-index: STALE region(s): " + ", ".join(stale))
            print("The component inventory is generated from the plugins/ tree.")
            print("Run: python3 scripts/update-component-index.py")
            return 1
        print("update-component-index: all regions current (%d components)." % len(rows))
        return 0

    if changed:
        print("update-component-index: rewrote " + ", ".join(changed))
    else:
        print("update-component-index: already current (%d components)." % len(rows))
    return 0


if __name__ == "__main__":
    sys.exit(main())
